vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        profile_image:
            uri_prefix: /images/profile_images
            upload_destination: "%kernel.project_dir%/public/images/profile_images"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
