vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        profile_image:
            uri_prefix: /images/Users/default.png
            upload_destination: "%kernel.project_dir%/public/images/Users/default.png"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
